// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	entity "TestSeparation/internal/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UsersRepository is an autogenerated mock type for the UsersRepository type
type UsersRepository struct {
	mock.Mock
}

// ByField provides a mock function with given fields: ctx, field, value
func (_m *UsersRepository) ByField(ctx context.Context, field string, value interface{}) (entity.User, error) {
	ret := _m.Called(ctx, field, value)

	if len(ret) == 0 {
		panic("no return value specified for ByField")
	}

	var r0 entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) (entity.User, error)); ok {
		return rf(ctx, field, value)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) entity.User); ok {
		r0 = rf(ctx, field, value)
	} else {
		r0 = ret.Get(0).(entity.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, interface{}) error); ok {
		r1 = rf(ctx, field, value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, user
func (_m *UsersRepository) Create(ctx context.Context, user *entity.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUsersRepository creates a new instance of UsersRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsersRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsersRepository {
	mock := &UsersRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
